# action.yaml
name: 'Create Expanse Change Ticket'
description: 'A GitHub Action that opens a expanse change ticket'
inputs:
  subject:
    description: 'A short description placeholder that will be used in the name of the change ticket'
    required: true
    default: "Test expanse change"
outputs:
  num_squared:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python src/get_num_square.py >>$GITHUB_OUTPUT
      shell: bash
