# .github/workflows/test_action.yaml
name: Test Action
on: #[push]
  workflow_dispatch:
  
jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch num squared
        id: get_square
        uses: ./actions/ 
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"
